version: "3.6"


services:
  sel:
    network_mode: host
    image: selenium/standalone-chrome
    restart: always
    ports:
    - 4444:4444

  app:
    build: .
    depends_on:
      - sel
    network_mode: host
