"""add tables from sqlalchemy

Revision ID: 510b885a85d9
Revises: 260d85549e34
Create Date: 2021-01-16 11:36:05.990326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510b885a85d9'
down_revision = '260d85549e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('born_date', sa.String(), nullable=True),
    sa.Column('born_location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    op.drop_table('author')
    # ### end Alembic commands ###
